# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='quotes',
            fields=[
                ('id_number', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('phone', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('type_info', models.CharField(max_length=70)),
                ('details', models.TextField()),
            ],
        ),
    ]
